//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public food()
        {
            this.organization_and_food = new HashSet<organization_and_food>();
            this.ready_menu_and_food = new HashSet<ready_menu_and_food>();
        }
    
        public int id { get; set; }
        public int category_id { get; set; }
        public int unit_id { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public string name { get; set; }
    
        public virtual food_category food_category { get; set; }
        public virtual food_units food_units { get; set; }
        public virtual ICollection<organization_and_food> organization_and_food { get; set; }
        public virtual ICollection<ready_menu_and_food> ready_menu_and_food { get; set; }
    }
}
