//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallery_titles
    {
        public int id { get; set; }
        public string title { get; set; }
        public string keywords { get; set; }
        public int category_id { get; set; }
    
        public virtual gallery_categories gallery_categories { get; set; }
    }
}
