//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_service
    {
        public organization_service()
        {
            this.organization_and_service = new HashSet<organization_and_service>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<organization_and_service> organization_and_service { get; set; }
    }
}
