//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ready_menu
    {
        public ready_menu()
        {
            this.ready_menu_and_food = new HashSet<ready_menu_and_food>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<ready_menu_and_food> ready_menu_and_food { get; set; }
    }
}
