//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_food_menu
    {
        public int id { get; set; }
        public string name { get; set; }
        public int site_menu_id { get; set; }
        public string image_name { get; set; }
        public string description { get; set; }
    
        public virtual site_menu site_menu { get; set; }
    }
}
