//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class akgul_yemek_dbEntities : DbContext
    {
        public akgul_yemek_dbEntities()
            : base("name=akgulcatering_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<details> details { get; set; }
        public DbSet<food> food { get; set; }
        public DbSet<food_category> food_category { get; set; }
        public DbSet<food_units> food_units { get; set; }
        public DbSet<gallery_categories> gallery_categories { get; set; }
        public DbSet<gallery_images> gallery_images { get; set; }
        public DbSet<gallery_titles> gallery_titles { get; set; }
        public DbSet<organization_and_food> organization_and_food { get; set; }
        public DbSet<organization_and_service> organization_and_service { get; set; }
        public DbSet<organization_information> organization_information { get; set; }
        public DbSet<organization_service> organization_service { get; set; }
        public DbSet<organization_type> organization_type { get; set; }
        public DbSet<ready_menu> ready_menu { get; set; }
        public DbSet<ready_menu_and_food> ready_menu_and_food { get; set; }
        public DbSet<site_food_menu> site_food_menu { get; set; }
        public DbSet<site_menu> site_menu { get; set; }
        public DbSet<slider> slider { get; set; }
        public DbSet<user> user { get; set; }
    }
}
