//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_units
    {
        public food_units()
        {
            this.food = new HashSet<food>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<food> food { get; set; }
    }
}
