//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallery_categories
    {
        public gallery_categories()
        {
            this.gallery_titles = new HashSet<gallery_titles>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<gallery_titles> gallery_titles { get; set; }
    }
}
