//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_and_food
    {
        public int id { get; set; }
        public int organization_information_id { get; set; }
        public int food_id { get; set; }
        public int quantity { get; set; }
        public float price { get; set; }
        public float total_price { get; set; }
        public int people_count { get; set; }
    
        public virtual food food { get; set; }
        public virtual organization_information organization_information { get; set; }
    }
}
