//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ready_menu_and_food
    {
        public int id { get; set; }
        public int ready_menu_id { get; set; }
        public int food_id { get; set; }
        public int quantity { get; set; }
        public float price { get; set; }
    
        public virtual food food { get; set; }
        public virtual ready_menu ready_menu { get; set; }
    }
}
