//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_menu
    {
        public site_menu()
        {
            this.site_food_menu = new HashSet<site_food_menu>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<site_food_menu> site_food_menu { get; set; }
    }
}
